# Generated by Django 5.0 on 2024-01-05 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0013_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 5, 8, 7, 26, 607121, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
