# Generated by Django 5.0 on 2024-01-07 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0015_alter_disposablecode_expires_at_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 7, 3, 23, 24, 972836, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
