# Generated by Django 5.0 on 2024-01-07 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0017_alter_disposablecode_expires_at_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 1, 7, 4, 5, 57, 274774, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
